In [1]:
import numpy as np

In [80]:
np.random.seed(0)
A = np.random.randint(0,10,[5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

# Methodes ndarray

In [90]:
A.sum()

2622

In [12]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [13]:
A.prod()

0

In [14]:
A.min()

0

In [15]:
A.min(axis=0)

array([3, 0, 3])

In [16]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [17]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

# Statistique

In [18]:
A.mean()

4.5

In [19]:
A.std()

2.9297326385411577

In [20]:
A.var()

8.583333333333334

In [89]:
np.corrcoef(A)

array([[ 1.        ,  0.14832409, -0.51131306,  0.44193628,  0.00723948,
         0.97830354,  0.95197554, -0.89635855,  0.12650757,  0.23725837],
       [ 0.14832409,  1.        ,  0.07679133, -0.11679277, -0.11497297,
         0.13217622,  0.25119742, -0.49308697,  0.03821111, -0.31851963],
       [-0.51131306,  0.07679133,  1.        ,  0.26581877, -0.69555573,
        -0.32745826, -0.61508865,  0.27319442,  0.69363515,  0.5816017 ],
       [ 0.44193628, -0.11679277,  0.26581877,  1.        , -0.09458336,
         0.56410523,  0.15186329, -0.29655622,  0.87168895,  0.65502382],
       [ 0.00723948, -0.11497297, -0.69555573, -0.09458336,  1.        ,
        -0.15412318, -0.00380085,  0.27726524, -0.4581754 , -0.73491303],
       [ 0.97830354,  0.13217622, -0.32745826,  0.56410523, -0.15412318,
         1.        ,  0.89351405, -0.90298966,  0.30966392,  0.42180647],
       [ 0.95197554,  0.25119742, -0.61508865,  0.15186329, -0.00380085,
         0.89351405,  1.        , -0.91345108

In [32]:
values, counts = np.unique(A, return_counts=True)

In [34]:
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3], dtype=int64)

In [39]:
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int64)

In [38]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [40]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


# NAN Corrections

In [42]:
A = np.random.randn(5,5)
A[0, 2] = np.nan #nan = not a number
A[4, 3] = np.nan
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [46]:
np.nanstd(A)

1.1017518326683546

In [51]:
np.isnan(A).sum()/A.size

0.08

In [52]:
A[np.isnan(A)] = 0
A

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

# Algebre lineaire

In [53]:
A = np.ones((2,3))
B = np.ones((3,2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [57]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [58]:
A = np.random.randint(0,10,[3,3])
A

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [59]:
np.linalg.det(A)

23.999999999999993

In [60]:
det(A)

NameError: name 'det' is not defined

In [61]:
np.linalg.inv(A)

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [-0.        ,  0.33333333, -0.33333333]])

In [62]:
np.linalg.pinv(A)

array([[-5.00000000e-01,  8.75000000e-01, -2.50000000e-01],
       [ 5.00000000e-01, -1.12500000e+00,  7.50000000e-01],
       [-1.57000667e-17,  3.33333333e-01, -3.33333333e-01]])

In [63]:
#valeur propre, vecteur propre
np.linalg.eig(A)

(array([13.58872344, -3.        , -0.58872344]),
 array([[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
        [-5.73889829e-01,  2.12013389e-16, -7.73940635e-01],
        [-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]))

# Exercice

Standardisez la matrice A sur chaque colonne.
(A-Abarre)/ecarttypedeA
Resultat: chaque colonne doit avoir moyenne = 0 et ecart type = 1

In [82]:
np.random.seed(0)
A = np.random.randint(0,100,[10,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [83]:
B = (A - A.mean(axis = 0))/A.std(axis = 0)

In [84]:
B

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [85]:
B.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [86]:
B.std(axis=0)

array([1., 1., 1., 1., 1.])

In [88]:
A-A.mean(axis=0) #Broadcasting !

array([[ -0.5,   0. ,   3.5,  21.3,   2.5],
       [-35.5,  36. , -39.5,  -9.7,  22.5],
       [ 25.5,  41. ,  27.5, -33.7,  -6.5],
       [ 20.5,  -8. ,  26.5,   0.3,  23.5],
       [ 36.5, -10. , -35.5,  31.3,   7.5],
       [-35.5, -27. ,  19.5,  23.3,  14.5],
       [  2.5,  17. ,  21.5,  53.3,  23.5],
       [  4.5, -18. , -41.5, -26.7, -50.5],
       [ -5.5, -15. ,   4.5, -36.7,  -7.5],
       [-12.5, -16. ,  13.5, -22.7, -29.5]])