In [1]:
import numpy as np

In [3]:
A = np.array([1, 2, 3])
A.shape

(3,)

In [6]:
B = np.zeros((3,2))
type(B.shape)

tuple

In [7]:
C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
D = np.full((2,3),9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [11]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 10, 20, dtype=np.float64)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Manipulation

In [18]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [19]:
print(A)
print(B)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
C = np.hstack((A,B))
C.shape

(3, 4)

In [24]:
D = np.vstack((A,B))
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
D.shape

(6, 2)

In [27]:
np.concatenate((A,B), axis = 1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [28]:
D = D.reshape((3,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
A = np.array([1,2,3])
A = A.reshape((A.shape[0], 1))
A.shape

(3, 1)

In [31]:
A = A.squeeze() #faire disparaaitre les dimensions a 1
A.shape

(3,)

In [32]:
#ravel: aplatir un tableau a 1 dimension
D = D.reshape((3,4))
D.ravel().shape

(12,)

In [33]:
def initialisation(m, n):
    #m : nombre de lignes
    #n : nombre de colonnes
    #retourne une matrice aleatoire (m, n+1)
    #avec une colonne biais (remplie de "1") tout a droite
    A = np.random.randn(m,n)
    B = np.ones((m,1))
    
    return np.concatenate((A,B), axis = 1)

In [36]:
initialisation(3,2)

array([[-1.61389785, -0.21274028,  1.        ],
       [-0.89546656,  0.3869025 ,  1.        ],
       [-0.51080514, -1.18063218,  1.        ]])